// src/global/constants/ResponseCode.ts

export const ErrorCode = {
    // COMMON
    INTERNAL_SERVER_ERROR: 'COMMON_000',
    INVALID_REQUEST: 'COMMON_001',
    METHOD_NOT_ALLOWED: 'COMMON_002',
    UNSUPPORTED_MEDIA_TYPE: 'COMMON_003',
    NOT_FOUND: 'COMMON_004',
    VALIDATION_FAIL: 'COMMON_005',
    EMPTY_BODY: 'COMMON_006',
    MISSING_PARAMETER: 'COMMON_007',

    // AUTH
    UNAUTHORIZED: 'AUTH_001',
    INVALID_TOKEN: 'AUTH_002',
    EXPIRED_TOKEN: 'AUTH_003',
    FORBIDDEN: 'AUTH_004',
    LOGIN_FAILED: 'AUTH_005',
    LOGIN_TRY_EXCEEDED: 'AUTH_006',
    LOGOUT_FAILED: 'AUTH_007',

    // USER
    DUPLICATE_EMAIL: 'USER_001',
    USER_NOT_FOUND: 'USER_002',
    PASSWORD_MISMATCH: 'USER_003',
    INVALID_NEW_PASSWORD: 'USER_004',
    SAME_AS_OLD_PASSWORD: 'USER_005',
    WITHDRAWN_USER: 'USER_006',
    PROFILE_IMAGE_NOT_FOUND: 'USER_007',
    FILE_TOO_LARGE: 'USER_008',
    UNSUPPORTED_FILE_TYPE: 'USER_009',
    INVALID_VERIFICATION_CODE: 'USER_010',
    EXPIRED_VERIFICATION_CODE: 'USER_011',
    TOO_MANY_REQUESTS: 'USER_012',

    // KAKAO
    KAKAO_AUTH_FAILED: 'KAKAO_001',
    INVALID_KAKAO_AUTH_CODE: 'KAKAO_002',
    KAKAO_BAD_GATEWAY: 'KAKAO_003',
    KAKAO_EMAIL_CONFLICT: 'KAKAO_004',

    // SUBJECT
    SUBJECT_NOT_FOUND: 'SUBJECT_001',
    DUPLICATE_SUBJECT_NAME: 'SUBJECT_002',
    INVALID_SUBJECT_COLOR: 'SUBJECT_003',
    SUBJECT_DELETE_NOT_ALLOWED: 'SUBJECT_004',
    SUBJECT_FORBIDDEN: 'SUBJECT_005',

    // RESOURCE
    RESOURCE_NOT_FOUND: 'RESOURCE_001',
    INVALID_UNIT_COUNT: 'RESOURCE_002',
    INVALID_PROGRESS_VALUE: 'RESOURCE_003',
    RESOURCE_FORBIDDEN: 'RESOURCE_004',
    RESOURCE_DELETE_NOT_ALLOWED: 'RESOURCE_005',

    // PLAN
    PLAN_NOT_FOUND: 'PLAN_001',
    INVALID_TARGET_DATE: 'PLAN_002',
    INVALID_PRIORITY: 'PLAN_003',
    PLAN_ALREADY_DONE: 'PLAN_004',
    PLAN_FORBIDDEN: 'PLAN_005',
    PLAN_VISIBILITY_NOT_ALLOWED: 'PLAN_006',

    // TIMER
    TIMER_ALREADY_RUNNING: 'TIMER_001',
    TIMER_NOT_RUNNING: 'TIMER_002',
    INVALID_TIMER_TIME: 'TIMER_003',
    TIMER_ALREADY_ENDED: 'TIMER_004',
    INVALID_MANUAL_TIME: 'TIMER_005',
    TIMER_RATE_LIMIT: 'TIMER_006',
    TIMER_CONCURRENCY_CONFLICT: 'TIMER_007',
    TIMER_MAX_TIME_EXCEEDED: 'TIMER_008',
    TIMER_ALREADY_PAUSED: 'TIMER_009',

    // REFLECTION
    REFLECTION_NOT_FOUND: 'REFLECT_001',
    REFLECTION_ALREADY_EXISTS: 'REFLECT_002',
    REFLECTION_FORBIDDEN: 'REFLECT_003',
    INVALID_REFLECTION_CONTENT: 'REFLECT_004',

    // TODOLIST
    TODO_NOT_FOUND: 'TODO_001',
    TODO_FORBIDDEN: 'TODO_002',
    INVALID_TODO_DATE: 'TODO_003',
    TODO_ALREADY_COMPLETED: 'TODO_004',
    INVALID_TODO_CONTENT: 'TODO_005',

    // STATS
    INVALID_STATS_RANGE: 'STATS_001',
    STATS_RANGE_TOO_LARGE: 'STATS_002',
    STATS_CALCULATION_ERROR: 'STATS_003',

    // GROUP
    GROUP_NOT_FOUND: 'GROUP_001',
    GROUP_FULL: 'GROUP_002',
    NOT_GROUP_MEMBER: 'GROUP_003',
    GROUP_ADMIN_REQUIRED: 'GROUP_004',
    ALREADY_GROUP_MEMBER: 'GROUP_005',
    GROUP_JOIN_PENDING: 'GROUP_006',
    INVALID_GROUP_PASSWORD: 'GROUP_007',
    CANNOT_KICK_TARGET: 'GROUP_008',
    INVALID_GROUP_SETTING: 'GROUP_009',
    INVITE_LINK_EXPIRED: 'GROUP_010',

    // LIKE / RANK
    LIKE_ALREADY_SENT: 'LIKE_001',
    LIKE_SELF_NOT_ALLOWED: 'LIKE_002',
    LIKE_GROUP_MEMBER_ONLY: 'LIKE_003',
    INVALID_RANK_FILTER: 'RANK_001',
    RANK_CALCULATION_ERROR: 'RANK_002',

    // NOTIFICATION
    NOTIFICATION_SEND_FAILED: 'NOTI_001',
    INVALID_NOTIFICATION_SETTING: 'NOTI_002',
    NOTIFICATION_TARGET_NOT_FOUND: 'NOTI_003',

    // INFRA
    SERVICE_UNAVAILABLE: 'INFRA_001',
    REDIS_ERROR: 'REDIS_001',
    RATE_LIMIT: 'RATE_001',
    LOCK_FAIL: 'LOCK_001',

} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

export const SuccessCode = {
    // COMMON
    OK: 'SUCCESS_200',
    CREATED: 'SUCCESS_201',
    NO_CONTENT: 'SUCCESS_204',

    // AUTH
    LOGIN_SUCCESS: 'AUTH_200',
    LOGOUT_SUCCESS: 'AUTH_201',
    TOKEN_REISSUE_SUCCESS: 'AUTH_202',

    // USER
    SIGNUP_SUCCESS: 'USER_201',
    WITHDRAW_SUCCESS: 'USER_204',
    PASSWORD_CHANGE_SUCCESS: 'USER_200',
    PROFILE_IMAGE_UPLOAD_SUCCESS: 'USER_205',
    PROFILE_IMAGE_UPDATE_SUCCESS: 'USER_206',
    PROFILE_IMAGE_DELETE_SUCCESS: 'USER_207',

    // SUBJECT
    SUBJECT_CREATE_SUCCESS: 'SUBJECT_201',
    SUBJECT_UPDATE_SUCCESS: 'SUBJECT_200',
    SUBJECT_DELETE_SUCCESS: 'SUBJECT_204',
    SUBJECT_LIST_SUCCESS: 'SUBJECT_200_1',

    // RESOURCE
    RESOURCE_CREATE_SUCCESS: 'RESOURCE_201',
    RESOURCE_UPDATE_SUCCESS: 'RESOURCE_200',
    RESOURCE_DELETE_SUCCESS: 'RESOURCE_204',
    RESOURCE_LIST_SUCCESS: 'RESOURCE_200_1',
    RESOURCE_DETAIL_SUCCESS: 'RESOURCE_200_2',

    // PLAN
    PLAN_CREATE_SUCCESS: 'PLAN_201',
    PLAN_UPDATE_SUCCESS: 'PLAN_200',
    PLAN_DELETE_SUCCESS: 'PLAN_204',
    PLAN_COMPLETE_SUCCESS: 'PLAN_200_1',
    PLAN_LIST_BY_DATE_SUCCESS: 'PLAN_200_2',

    // TIMER
    TIMER_START_SUCCESS: 'TIMER_200',
    TIMER_END_SUCCESS: 'TIMER_200_1',
    TIMER_AUTO_END_SUCCESS: 'TIMER_200_2',
    STUDY_LOG_LIST_SUCCESS: 'TIMER_200_3',
    STUDY_LOG_SUMMARY_SUCCESS: 'TIMER_200_4',
    TIMER_STATUS_SUCCESS: 'TIMER_200_5',
    TIMER_PAUSE_SUCCESS: 'TIMER_200_6',
    TIMER_RESUME_SUCCESS: 'TIMER_200_7',
    MANUAL_STUDY_LOG_SUCCESS: 'TIMER_201',

    // REFLECTION
    REFLECTION_CREATE_SUCCESS: 'REFLECT_201',
    REFLECTION_UPDATE_SUCCESS: 'REFLECT_200',
    REFLECTION_DELETE_SUCCESS: 'REFLECT_204',
    REFLECTION_DAILY_SUCCESS: 'REFLECT_200_1',
    REFLECTION_LIST_SUCCESS: 'REFLECT_200_2',

    // TODOLIST
    TODO_CREATE_SUCCESS: 'TODO_201',
    TODO_UPDATE_SUCCESS: 'TODO_200',
    TODO_DELETE_SUCCESS: 'TODO_204',
    TODO_STATUS_UPDATE_SUCCESS: 'TODO_200_1',
    TODO_LIST_SUCCESS: 'TODO_200_2',
    TODO_LIST_BY_DATE_SUCCESS: 'TODO_200_3',

    // STATS / DASHBOARD
    DASHBOARD_MAIN_SUCCESS: 'STATS_200',
    WEEKLY_STATS_SUCCESS: 'STATS_200_1',
    MONTHLY_STATS_SUCCESS: 'STATS_200_2',
    ATTENDANCE_CALENDAR_SUCCESS: 'STATS_200_3',

    // GROUP
    GROUP_CREATE_SUCCESS: 'GROUP_201',
    GROUP_JOIN_SUCCESS: 'GROUP_200',
    GROUP_JOIN_REQUEST_SUCCESS: 'GROUP_200_1',
    GROUP_MEMBER_LIST_SUCCESS: 'GROUP_200_2',
    GROUP_ROLE_UPDATE_SUCCESS: 'GROUP_200_3',
    GROUP_KICK_SUCCESS: 'GROUP_204',
    GROUP_PLAN_LIST_SUCCESS: 'GROUP_200_4',

    // RANK / LIKE
    GROUP_RANKING_SUCCESS: 'RANK_200',
    LIKE_SEND_SUCCESS: 'LIKE_201',

    // NOTIFICATION
    NOTIFICATION_LIST_SUCCESS: 'NOTI_200',
    NOTIFICATION_READ_SUCCESS: 'NOTI_200_1',
    NOTIFICATION_SETTING_UPDATE_SUCCESS: 'NOTI_200_2',

} as const;

export type SuccessCode = typeof SuccessCode[keyof typeof SuccessCode];

/**
 * HTTP 상태 코드와 기본 ErrorCode 매핑
 * 특정 도메인 에러가 아닌 일반적인 HTTP 상황에 대한 기본값
 */
export const HTTP_STATUS_TO_ERROR_CODE: Record<number, ErrorCode> = {
    400: ErrorCode.INVALID_REQUEST,
    401: ErrorCode.UNAUTHORIZED,
    403: ErrorCode.FORBIDDEN,
    404: ErrorCode.NOT_FOUND,
    405: ErrorCode.METHOD_NOT_ALLOWED,
    409: ErrorCode.LOCK_FAIL,
    413: ErrorCode.FILE_TOO_LARGE,
    429: ErrorCode.TOO_MANY_REQUESTS,
    500: ErrorCode.INTERNAL_SERVER_ERROR,
    503: ErrorCode.SERVICE_UNAVAILABLE,
};